many_files = ['WhatsApp Image 2017-06-10 at 9.53.02 PM.jpeg',
 'unnamed.png',
 'index.php',
 'wp-settings.php',
 'WallPaper.zip',
 'coverage-4.4.1.tar.gz',
 'Coldplay - The Scientist.mp4',
 'GBWAPlus v5.60-2.17.146 @atnfas_hoak.apk',
 'updates to www.thetruenorth.co.ke 01.pptx',
 'pyinstaller-draft1a-35x35-trans.png',
 'The 100',
 'WhatsApp Image 2017-06-05 at 09.19.55.jpeg',
 'phantomjs-2.1.1-linux-i686.tar.bz2',
 'updates to www.thetruenorth.co.ke 01 (1).pptx',
 'striped',
 'Ghetto Kids dancing StyleZo(Kadondo) by Eddy Kenzo.mp4',
 'WhatsApp Image 2017-06-14 at 2.26.53 PM.jpeg',
 'third-party.txt',
 'LEARNING_PYTHON_APPLICATION_DEVELOPMENT.pdf',
 'Itemized_Project_Budget.xlsx',
 'ic_arrow_drop_up_black_24dp',
 'wp-signup.php',
 'step2DSC_5382-280x187.jpg',
 'Instagram.zip',
 'wp-cron.php',
 'ChangeLog',
 '.~lock.Giant.docx#',
 'phantomjs-2.1.1-linux-i686',
 'GBWhatsApp Images.zip',
 'wp-activate.php',
 'Arrow',
 'NON DISCLOSURE AGREEMENT SHALOM (1).doc',
 'Service Agreement- photography.(1).doc',
 'directions-shalom.png',
 'Photo Grid.zip',
 'wp-links-opml.php',
 'striped.zip',
 'step3DSC_5395-280x187.jpg',
 'Pictures.zip',
 'wp-blog-header.php',
 'wp-admin',
 'pentaho-libxml.ymp',
 'Screenshot_2017-03-09-23-13-40.png',
 'wp-trackback.php',
 'skypeforlinux-64.rpm',
 'heroku-linux-amd64.tar.gz',
 'teamdroidicon.png',
 'tdicon.png',
 'web-stanford-edu.pdf',
 'thetruen_wp999.sql',
 'wordpress-4.6.6.zip',
 'A Terrific Dancing Trio Performs!.mp4',
 'wp-comments-post.php',
 'wp-content',
 'Survey.docx',
 'shallom directions.png',
 'Google Play Supported Devices - Sheet 1.pdf',
 'step1DSC_5540-280x187.jpg',
 'Bluetooth.zip',
 'IA LISTING, 2017-3.docx',
 'xmlrpc.php',
 '.directory',
 'Files_downloaded_by_AirDroid.zip',
 'license.txt',
 'JD IT Officer.pdf',
 'NON DISCLOSURE AGREEMENT SHALOM.doc',
 'mozilla_science_mini_grant_application_response_C3UQj5RU5ajv.pdf',
 'Handel Messiah Full Score.pdf',
 'GBWhatsapp Profile Photos.zip',
 'wp-load.php',
 'wp-includes',
 'optimizilla.zip',
 'optimizilla',
 'Download.zip',
 'unnamed.webp',
 'wp-config-sample.php',
 't-20',
 'comment.png',
 'unnamed (1).png',
 'wp-login.php',
 'LICENSE',
 'Gumba Free Website Template - Free-CSS.com.zip',
 'gumba-0.1.0',
 'Consent Form.docx',
 'MP4',
 'wordpress-4.7.5.zip',
 'LICENSE.BSD',
 'readme.html',
 'README.md',
 'ZIP',
 'ic_arrow_drop_up_black_24dp.zip',
 'index.html',
 '1-IMGP8786 copy-min.jpg',
 'DSC03477-min.jpg',
 'LICENSE.md',
 'Remix_OS_for_PC_Android_M_64bit_B2016112101',
 'MKV',
 'wp-mail.php',
 'Remix_OS_for_PC_Android_M_64bit_B2016112101.zip',
 'Mozilla-global-sprint-kisumu-kenya-ticket-TURH-1.pdf',
 'SUSE_Geeko_plush_toy.jpg',
 'Sample 2.docx',
 'html5up-editorial.zip',
 'blindspot.207.hdtv-lol[ettv].mkv',
 'blindspot.208.hdtv-lol[ettv].mkv',
 'Jennifer Hudson - Where You At.mp4',
 'Cholera outbreak in Kenya_24062017 (2).pdf',
 'Cholera outbreak in Kenya_24062017 (1).pdf',
 'html5up-editorial',
 'Telegram Desktop',
 'Sample 1.docx',
 'software tester.jpg',
 'T-20 Free Website Template - Free-CSS.com.zip',
 'Resize me Free Website Template - Free-CSS.com.zip',
 'developer pic.png',
 'Git-2.13.1.2-32-bit.exe',
 'pykaraoke-0.7.5.zip',
 'pykaraoke-0.7.5',
 'Cholera outbreak in Kenya_24062017.pdf',
 'Khaligraph Jones - Chizi Karaoke.mp3',
 '7f720a6b430e9acf6855dda668f01cd1--software-testing-software-development.jpg',
 'The Chainsmokers & Coldplay - Something Just Like This (Unofficial Music '
 'Video).mp4',
 'One Direction - Story of My Life.mp4',
 'T104_TranscribeMe Style Guide V1.2.pdf']

few_files = ['WhatsApp Image 2017-06-10 at 9.53.02 PM.jpeg',
 'unnamed.png',
 'index.php',
 'wp-settings.php',
 'WallPaper.zip',
 'coverage-4.4.1.tar.gz',
 'Coldplay - The Scientist.mp4',
 'GBWAPlus v5.60-2.17.146 @atnfas_hoak.apk',
 'updates to www.thetruenorth.co.ke 01.pptx',
 'pyinstaller-draft1a-35x35-trans.png']